### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by sofvanh** [porrasm/otm-harjoitustyo#1]
Koodi ladattu 3.5.klo 12:20

En saanut koodia compilattua Linuxillani, enkä löytänyt Linuxille valmista buildia releaseista, joten pelitestaus jäi valitettavasti tekemättä.

### Holdem

- Monilla luokilla (esim. Card.cs) oli private muuttujia, ja lisäksi sitä jotenkin vastaavat public muuttujat, joilla oli getterit ja setterit
  - Jos haluat, että muuttuja on private mutta ulkoapäin käsiteltävissä, tee private muuttuja jolla getteri ja setteri
  - Jos haluat public luokan, se ei tarvitse getteriä eikä setteriä
    - Vaan sitä voi helposti muokata tyyliin instanssi.muuttuja = 1
- Card, Deck, Hand ja Turn ovat hyviä sovelluslogiikasta huolehtivia luokkia, koska niillä ei ole riippuvuuksia Unityn vaikeasti mockattaviin luokkiin. Näille siis kannattaa kirjoittaa yksikkötestejä, koska refaktoroinnin tarvetta ei ole. (ks. kohta Muusta / Testaus)

### Networking

- Tyhjien skriptien tarkoitus jäi epäselväksi

### Release

- Olisi parempi, jos joka järjestelmälle olisi omat .zip-tiedostot
- ...ja Linuxille olisi myös hyvä olla buildi

### Git

- Kannattaa committaa useammin ja kirjoittaa parempia commit messageja. Se selkeyttää omaa workflow'ta ja on todella iso apu, jos joskus mokaa jotain.

### Testaus

- Unit testeihin kannattaa panostaa ennen integraatiotestejä
  - Avuksi: [Tämä](https://blogs.unity3d.com/2014/06/03/unit-testing-part-2-unit-testing-monobehaviours/) Unityn julkaisema postaus oli minulle suureksi avuksi, kun pohdin, miten kirjoittaa testattavaa koodia Unitylle

Tsemppiä loppukurssiin!

**Comment by porrasm** [comment]
Kiitos koodikatselmoinnista, itseltä jäi tekemättä.

Yksi kommentti private muuttujista:
"Monilla luokilla (esim. Card.cs) oli private muuttujia, ja lisäksi sitä jotenkin vastaavat public muuttujat, joilla oli getterit ja setterit"

Nämä public muuttujat ovat gettereitä ja settereitä, mutta niiden käyttö toimii vain eri lailla.
private int luku;
public int Luku { get { return luku; } set { luku = value; } } 

Minusta tämä on selkeämpi tapa joihinkin tapauksiin. Esim jos halutaan kasvattaa lukua yhdellä.
luokka.SetLuku(luokka.GetLuku() + 1); vs luokka.Luku++;

Kiitos tuosta Unity blogista testeihin. Olen siitä vielä itse lähes täysin pihalla.
